import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>TasksManger.com - Home</title>
        <meta name="Home" content="initial-scale=1.0, width=device-width" />
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-24">
        <div className="mx-24 my-3 flex flex-col bg-white rounded-lg border shadow-md md:flex-row md:max-w-3/4 hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
          <img
            style={{ height: "55vh" }}
            className="object-cover w-full rounded-t-lg md:w-96 md:rounded-none md:rounded-l-lg"
            src="https://picsum.photos/600/400/?random"
            alt=""
          />
          <div className="flex flex-col justify-between p-4 leading-normal">
            <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              Tasks Manager
            </h5>
            <h6 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              Developed by: Hritwik Agarwal
            </h6>
            <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
              A mini project using NextJs, MongoDB Atlas, Express, NodeJs and
              Taiwind.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
