import { useState } from "react";
import Link from "next/link";
import Head from "next/head";
import axios from "axios";
import { useRouter } from "next/router";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import PhoneInput from "react-phone-number-input";
import "react-phone-number-input/style.css";
import Navbar from "../components/Navbar";

toast.configure();
const signin = () => {
  const router = useRouter();
  const [userPhone, setUserPhone] = useState("");

  const loginUser = (e) => {
    e.preventDefault();
    if (userPhone === "") {
      toast.error("Phone Number is Required", {
        position: toast.POSITION.BOTTOM_RIGHT,
      });
    } else {
      try {
        const user = { userphone: userPhone };
        axios
          .post(`http://localhost:3000/User/getUser`, user)
          .then((res) => {
            if (res.status == 201) {
              router.push("/tasks");
              toast.success(res.data.message, {
                position: toast.POSITION.BOTTOM_RIGHT,
              });
            } else {
              toast.error(res.data.message, {
                position: toast.POSITION.BOTTOM_RIGHT,
              });
            }
          })
          .catch((error) => {
            console.log(error);
          });
      } catch (error) {
        console.log(error);
      }
    }
  };

  return (
    <>
      <Head>
        <title>TasksManger.com - Login</title>
        <meta name="Login" content="initial-scale=1.0, width=device-width" />
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className="h-screen">
        <div className="px-6 h-full text-gray-800">
          <div className="flex xl:justify-center lg:justify-between justify-center items-center flex-wrap h-full g-6">
            <div className="grow-0 shrink-1 md:shrink-0 basis-auto xl:w-6/12 lg:w-6/12 md:w-9/12 mb-12 md:mb-0">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                className="w-full"
                alt="Sample image"
              />
            </div>
            <div className="xl:ml-20 xl:w-5/12 lg:w-5/12 md:w-8/12 mb-12 md:mb-0">
              <form>
                {/* <!-- Phone Number input --> */}
                <div className="mb-6">
                  <PhoneInput
                    className="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                    placeholder="Enter phone number"
                    defaultCountry="IN"
                    onChange={setUserPhone}
                    value={userPhone}
                  />
                </div>

                <div className="text-center lg:text-left">
                  <button
                    type="button"
                    className="inline-block px-7 py-3 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
                    onClick={loginUser}
                  >
                    Login
                  </button>
                  <p className="text-sm font-semibold mt-2 pt-1 mb-0">
                    Don't have an account?&nbsp;&nbsp;
                    <Link href="/register">
                      <a className="cursor-pointer text-red-600 hover:text-red-700 focus:text-red-700 transition duration-200 ease-in-out">
                        Register
                      </a>
                    </Link>
                  </p>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};
export default signin;
