import Head from "next/head";
import React, { useState } from "react";
import TasksRibbon from "../components/TasksRibbon";
import ShowTask from "../components/ShowTask";
const tasks = () => {
  const [showTaskModal, setShowTaskModal] = useState(false);

  function handleChange(newValue) {
    setShowTaskModal(newValue);
  }

  return (
    <>
      <Head>
        <title>Tasks</title>
        <meta name="Tasks" content="initial-scale=1.0, width=device-width" />
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container my-12 mx-auto px-4 md:px-12">
        <TasksRibbon />
        <div className="flex flex-wrap -mx-1 lg:-mx-4">
          {/* <!-- Column --> */}
          <div className="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
            {/* <!-- Article --> */}
            <article className="overflow-hidden rounded-lg shadow-lg">
              <a onClick={() => setShowTaskModal(true)}>
                <img
                  alt="Placeholder"
                  className="block h-auto w-full"
                  src="https://picsum.photos/600/400/?random"
                />
              </a>

              <header
                onClick={() => setShowTaskModal(true)}
                className="flex items-center justify-between leading-tight p-2 md:p-4"
              >
                <h1 className="text-lg">
                  <a
                    className="no-underline hover:underline text-black"
                    href="#"
                  >
                    Article Title
                  </a>
                </h1>
                <p className="text-grey-darker text-sm">11/1/19</p>
              </header>
            </article>
            {/* <!-- END Article --> */}
          </div>
          {/* <!-- END Column --> */}
        </div>
      </div>
      {showTaskModal ? (
        <ShowTask value={setShowTaskModal} onChange={handleChange} />
      ) : null}
    </>
  );
};
export default tasks;
